# Generated by Django 4.0.2 on 2022-03-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_open',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
